# Generated by Django 4.0.4 on 2022-05-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_deletion_comment_item_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
    ]
