# Generated by Django 4.0.4 on 2022-05-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_is_deleted_item_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deletion_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
