# Generated by Django 4.0.4 on 2022-05-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_deletion_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
